behaviors:
  MyBehavior:  # Behavior name
    trainer_type: ppo  # Trainer type (e.g., ppo, sac, imitation)
    hyperparameters:  # Hyperparameters for training
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:  # Network settings
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:  # Reward signal settings
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000  # Max number of steps
    time_horizon: 64
    summary_freq: 10000  # Frequency of summaries (for TensorBoard)
    checkpoint_interval: 50000  # Interval for checkpoint saving
    keep_checkpoints: 5  # Number of checkpoints to keep

